name = "MyExample"
uuid = "61ddc7b5-b3c6-4179-96c2-e6b914c8e65c"
authors = ["Matthew Thompson"]
version = "0.1.0"

[compat]
julia = "1.6.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
